dataset:
  batch_size: 32
  description: ''
  group_label: condition
  h5ad_data: /lustre/groups/ml01/projects/2024_spatial_long_range_GT_francesca.drummer/data/cosmx_pancreas.h5ad
  layer_key: null
  name: melton25
  num_classes: -1
  num_features: -1
  pct_mask_nodes: 0.1
  prediction_level: node
  prediction_obs: cell_type_coarse
  prediction_task: regression
  sample_key: ["sliding_window_square", "sliding_window_v"]
  segmentation_robustness: null
  spatial_neigbors_kwargs:
    coord_type: generic
    library_key: slide_fov
    n_neighs: 6
    radius: 110
  split_key: split
  stratify_group: null
  test_size: 0.1
  train_size: 0.7
  val_size: 0.2
model:
  decoder:
    dropout_decoder: 0.1
    dual_decoder: true
    hidden_dims: [256, 128]
    type: linear
  global_component:
    latent_obsm_key: null
    name: self-attn-transformer
    parameters:
      activation_func: relu
      dim_feedforward: 256
      dropout_global: 0.0
      long_range_attention: false
      max_seq_len: 3000
      n_heads: 2
      num_layers: 4
      type_gex_embedding: null
  local_component:
    name: GCN
    parameters:
      dropout_local: 0.1
      hidden_dim: 512
      num_layers: 1
  loss: null
  n_embed: 128
  save: /lustre/groups/ml01/projects/2024_spatial_long_range_GT_francesca.drummer/results/melton25/
optim:
  accelerator: auto
  cross_corr: cell
  early_stopping: true
  loss: MSELoss
  lr: 0.005
  lr_max_epochs: 100
  lr_scheduler: CosineWarmupScheduler
  lr_warmup: 40
  n_epochs: 100
  seed: 44
  wd: 0.01
wandb:
  project_name: GTLongRange_CosmXPancreas
  use: true
